# Generated by Django 5.0.2 on 2024-03-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
                ("date_begin", models.DateField(db_comment="starting date of tax")),
                (
                    "date_end",
                    models.DateField(
                        blank=True, db_comment="ending date of tax", null=True
                    ),
                ),
                ("tax_name", models.CharField(max_length=20)),
                ("tax_rate", models.DecimalField(decimal_places=4, max_digits=10)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "tax_rate",
                "managed": False,
            },
        ),
    ]
