# Generated by Django 5.0.2 on 2024-03-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplieritem",
            fields=[
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
                ("supplier_item_code", models.CharField(blank=True, null=True)),
                ("supplier_item_description", models.CharField(blank=True, null=True)),
                ("unit_of_purchase", models.CharField(blank=True, null=True)),
                (
                    "quantity_unit_of_purchase_in_unit_of_usage",
                    models.FloatField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "supplieritem",
                "managed": False,
            },
        ),
    ]
