# Generated by Django 5.0.2 on 2024-03-01 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0002_supplieritem"),
    ]

    operations = []
