# Generated by Django 5.0.2 on 2024-03-01 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0003_force_migration"),
    ]

    operations = []
