# Generated by Django 5.0.2 on 2024-03-02 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0004_force_migration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supplieritem",
            options={"managed": True},
        ),
    ]
