# Generated by Django 5.0.2 on 2024-03-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jitsuitem",
            fields=[
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
                ("deleted_row", models.BooleanField(blank=True, null=True)),
                ("description", models.CharField()),
                ("unit_of_measure", models.CharField(blank=True, null=True)),
                ("cost_per_unit_of_measure", models.FloatField(blank=True, null=True)),
                ("alternate", models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                "db_table": "jitsuitem",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Jitsuitemcategory",
            fields=[
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
                ("deleted_row", models.BooleanField(blank=True, null=True)),
                ("description", models.CharField()),
            ],
            options={
                "db_table": "jitsuitemcategory",
                "managed": False,
            },
        ),
    ]
